#-O3 when compiling optmizes
hpsd:
	gcc -fopenmp -O3 hot_plate_single_dimention.c -o hot_plate_sd
hot:
	gcc -fopenmp -O3 hot_plate_final.c -o hot_plate_final 
test:
	gcc -Wall -g -fopenmp test.cpp -o test
omp_hello:
	gcc -fopenmp omp_hello.c -o omp_hello
