#-O3 when compiling optmizes
busy:
	gcc -lpthread -O3 hot_plate_busy_barrier.c -o hot_plate_busy
linear:
	gcc -lpthread -O3 hot_plate_linear_barrier.c -o hot_plate_linear
log:
	gcc -pthread -O3 hot_plate_log_barrier.c -o hot_plate_log
barriers:
	gcc -pthread -O3 hot_plate_barriers.c -o hot_plate_barriers
hot2:
	gcc -pthread -O3 hot_plate_v2.c -o hot_plate_v2
hot1:
	gcc -pthread -O3 hot_plate_first.c -o hot_plate_first
pthreads:
	gcc -pthread -O3 pthreads_pract.c -o threads
